-- MySQL Script generated by MySQL Workbench
-- Tue Jan 16 10:41:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`type_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`type_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`type_user` (
  `idtype_user` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idtype_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`people` ;

CREATE TABLE IF NOT EXISTS `mydb`.`people` (
  `idpeople` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `cpf` VARCHAR(20) NULL,
  `picture` VARCHAR(60) NULL,
  PRIMARY KEY (`idpeople`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `idpeople` INT NULL,
  `type_user` INT NOT NULL,
  `last_ip` VARCHAR(20) NULL,
  `login` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `hash` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`),
  INDEX `type_user_idx` (`type_user` ASC),
  INDEX `id_people_idx` (`idpeople` ASC),
  CONSTRAINT `type_user`
    FOREIGN KEY (`type_user`)
    REFERENCES `mydb`.`type_user` (`idtype_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_people`
    FOREIGN KEY (`idpeople`)
    REFERENCES `mydb`.`people` (`idpeople`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pacient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pacient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pacient` (
  `idpacient` INT NOT NULL,
  `idpeople` INT NULL,
  PRIMARY KEY (`idpacient`),
  INDEX `id_people_idx` (`idpeople` ASC),
  CONSTRAINT `id_people`
    FOREIGN KEY (`idpeople`)
    REFERENCES `mydb`.`people` (`idpeople`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`consult` ;

CREATE TABLE IF NOT EXISTS `mydb`.`consult` (
  `idconsult` INT NOT NULL,
  `iduser` INT NULL,
  `idpacient` INT NULL,
  `timestamp` DATETIME NULL,
  `date` DATE NULL,
  `ip_user` VARCHAR(20) NULL,
  `free_text` TEXT NULL,
  `have_files` TINYINT NULL,
  PRIMARY KEY (`idconsult`),
  INDEX `idpaciente_idx` (`idpacient` ASC),
  INDEX `iduser_idx` (`iduser` ASC),
  CONSTRAINT `idpaciente`
    FOREIGN KEY (`idpacient`)
    REFERENCES `mydb`.`pacient` (`idpacient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anamnese`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`anamnese` ;

CREATE TABLE IF NOT EXISTS `mydb`.`anamnese` (
  `idanamnese` INT NOT NULL,
  `idconsult` INT NULL,
  PRIMARY KEY (`idanamnese`),
  INDEX `idconsult_idx` (`idconsult` ASC),
  CONSTRAINT `idconsult`
    FOREIGN KEY (`idconsult`)
    REFERENCES `mydb`.`consult` (`idconsult`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`physical_exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`physical_exam` ;

CREATE TABLE IF NOT EXISTS `mydb`.`physical_exam` (
  `idphysical_exam` INT NOT NULL,
  `idconsult` INT NULL,
  PRIMARY KEY (`idphysical_exam`),
  INDEX `idconsult_idx` (`idconsult` ASC),
  CONSTRAINT `idconsult`
    FOREIGN KEY (`idconsult`)
    REFERENCES `mydb`.`consult` (`idconsult`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medicines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medicines` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medicines` (
  `idmedicines` INT NOT NULL,
  `idconsult` INT NULL,
  PRIMARY KEY (`idmedicines`),
  INDEX `idconsult_idx` (`idconsult` ASC),
  CONSTRAINT `idconsult`
    FOREIGN KEY (`idconsult`)
    REFERENCES `mydb`.`consult` (`idconsult`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`file` ;

CREATE TABLE IF NOT EXISTS `mydb`.`file` (
  `idfile` INT NOT NULL,
  `type` VARCHAR(10) NULL,
  PRIMARY KEY (`idfile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`file__consult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`file__consult` ;

CREATE TABLE IF NOT EXISTS `mydb`.`file__consult` (
  `idfile` INT NOT NULL,
  `idconsult` INT NULL,
  INDEX `idfile_idx` (`idfile` ASC),
  INDEX `idconsult_idx` (`idconsult` ASC),
  CONSTRAINT `idfile`
    FOREIGN KEY (`idfile`)
    REFERENCES `mydb`.`file` (`idfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idconsult`
    FOREIGN KEY (`idconsult`)
    REFERENCES `mydb`.`consult` (`idconsult`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comp_exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comp_exam` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comp_exam` (
  `idcomp_exam` INT NOT NULL,
  `idconsult` INT NULL,
  PRIMARY KEY (`idcomp_exam`),
  INDEX `idconsult_idx` (`idconsult` ASC),
  CONSTRAINT `idconsult`
    FOREIGN KEY (`idconsult`)
    REFERENCES `mydb`.`consult` (`idconsult`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (`id` INT, `type_user` INT, `login` INT, `pass` INT, `name` INT, `picture` INT);

-- -----------------------------------------------------
-- View `mydb`.`login`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`login` ;
DROP TABLE IF EXISTS `mydb`.`login`;
USE `mydb`;
CREATE  OR REPLACE VIEW `login` AS
SELECT u.id , u.type_user, u.login, u.pass, p.name, p.picture FROM user AS u
INNER JOIN people as p ON u.idpeople = p.idpeople;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
