-- MySQL Script generated by MySQL Workbench
-- Tue Jan 16 10:54:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `type_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `type_user` ;

CREATE TABLE IF NOT EXISTS `type_user` (
  `idtype_user` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idtype_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `people` ;

CREATE TABLE IF NOT EXISTS `people` (
  `idpeople` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `cpf` VARCHAR(20) NULL,
  `picture` VARCHAR(60) NULL,
  PRIMARY KEY (`idpeople`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `idpeople` INT NULL,
  `type_user` INT NOT NULL,
  `last_ip` VARCHAR(20) NULL,
  `login` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `hash` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`),
  INDEX `type_user_idx` (`type_user` ASC),
  INDEX `id_people_idx` (`idpeople` ASC),
  CONSTRAINT `type_user`
    FOREIGN KEY (`type_user`)
    REFERENCES `type_user` (`idtype_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_people_user`
    FOREIGN KEY (`idpeople`)
    REFERENCES `people` (`idpeople`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pacient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pacient` ;

CREATE TABLE IF NOT EXISTS `pacient` (
  `idpacient` INT NOT NULL,
  `idpeople` INT NULL,
  PRIMARY KEY (`idpacient`),
  INDEX `id_people_idx` (`idpeople` ASC),
  CONSTRAINT `id_people_pacient`
    FOREIGN KEY (`idpeople`)
    REFERENCES `people` (`idpeople`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consult` ;

CREATE TABLE IF NOT EXISTS `consult` (
  `idconsult` INT NOT NULL,
  `iduser` INT NULL,
  `idpacient` INT NULL,
  `timestamp` DATETIME NULL,
  `date` DATE NULL,
  `ip_user` VARCHAR(20) NULL,
  `free_text` TEXT NULL,
  `have_files` TINYINT NULL,
  PRIMARY KEY (`idconsult`),
  INDEX `idpaciente_idx` (`idpacient` ASC),
  INDEX `iduser_idx` (`iduser` ASC),
  CONSTRAINT `idpaciente_consult`
    FOREIGN KEY (`idpacient`)
    REFERENCES `pacient` (`idpacient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `iduser_consult`
    FOREIGN KEY (`iduser`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anamnese`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anamnese` ;

CREATE TABLE IF NOT EXISTS `anamnese` (
  `idanamnese` INT NOT NULL,
  `idconsult` INT NULL,
  PRIMARY KEY (`idanamnese`),
  INDEX `idconsult_idx` (`idconsult` ASC),
  CONSTRAINT `idconsult_anam`
    FOREIGN KEY (`idconsult`)
    REFERENCES `consult` (`idconsult`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `physical_exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `physical_exam` ;

CREATE TABLE IF NOT EXISTS `physical_exam` (
  `idphysical_exam` INT NOT NULL,
  `idconsult` INT NULL,
  PRIMARY KEY (`idphysical_exam`),
  INDEX `idconsult_idx` (`idconsult` ASC),
  CONSTRAINT `idconsult_physical`
    FOREIGN KEY (`idconsult`)
    REFERENCES `consult` (`idconsult`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medicines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicines` ;

CREATE TABLE IF NOT EXISTS `medicines` (
  `idmedicines` INT NOT NULL,
  `idconsult` INT NULL,
  PRIMARY KEY (`idmedicines`),
  INDEX `idconsult_idx` (`idconsult` ASC),
  CONSTRAINT `idconsult_medicine`
    FOREIGN KEY (`idconsult`)
    REFERENCES `consult` (`idconsult`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `file` ;

CREATE TABLE IF NOT EXISTS `file` (
  `idfile` INT NOT NULL,
  `type` VARCHAR(10) NULL,
  PRIMARY KEY (`idfile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `file__consult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `file__consult` ;

CREATE TABLE IF NOT EXISTS `file__consult` (
  `idfile` INT NOT NULL,
  `idconsult` INT NULL,
  INDEX `idfile_idx` (`idfile` ASC),
  INDEX `idconsult_idx` (`idconsult` ASC),
  CONSTRAINT `idfile`
    FOREIGN KEY (`idfile`)
    REFERENCES `file` (`idfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idconsult_file`
    FOREIGN KEY (`idconsult`)
    REFERENCES `consult` (`idconsult`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp_exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp_exam` ;

CREATE TABLE IF NOT EXISTS `comp_exam` (
  `idcomp_exam` INT NOT NULL,
  `idconsult` INT NULL,
  PRIMARY KEY (`idcomp_exam`),
  INDEX `idconsult_idx` (`idconsult` ASC),
  CONSTRAINT `idconsult_comp`
    FOREIGN KEY (`idconsult`)
    REFERENCES `consult` (`idconsult`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Placeholder table for view `login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login` (`id` INT, `type_user` INT, `login` INT, `pass` INT, `name` INT, `picture` INT);

-- -----------------------------------------------------
-- View `login`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `login` ;
DROP TABLE IF EXISTS `login`;
CREATE  OR REPLACE VIEW `login` AS
SELECT u.id , u.type_user, u.login, u.pass, p.name, p.picture FROM user AS u
INNER JOIN people as p ON u.idpeople = p.idpeople;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
